In [7]:
! pip3 install scikit-learn

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: scikit-learn in /Users/prishitasingh/Library/Python/3.9/lib/python/site-packages (1.6.1)
Requirement already satisfied: numpy>=1.19.5 in /Users/prishitasingh/Library/Python/3.9/lib/python/site-packages (from scikit-learn) (2.0.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /Users/prishitasingh/Library/Python/3.9/lib/python/site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: joblib>=1.2.0 in /Users/prishitasingh/Library/Python/3.9/lib/python/site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: scipy>=1.6.0 in /Users/prishitasingh/Library/Python/3.9/lib/python/site-packages (from scikit-learn) (1.13.1)
WARNING: You are using pip version 21.2.4; however, version 26.0.1 is available.
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.

In [8]:
import sklearn
print(sklearn.__version__)

1.6.1

In [9]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [10]:
import sys
print(sys.executable)

/Library/Developer/CommandLineTools/usr/bin/python3

In [11]:
df=pd.read_csv('/Users/prishitasingh/Desktop/Machine Learning/pandas/Titanic-Dataset.csv')
df['Survived'].value_counts()

Survived
0    549
1    342
Name: count, dtype: int64

In [12]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [14]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [15]:
df = df.drop(columns=["Cabin", "Name", "Ticket", "PassengerId"], errors="ignore")

In [16]:
df["Age"] = df["Age"].fillna(df["Age"].median())
df.dropna(subset=["Embarked"], inplace=True)

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 889 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  889 non-null    int64
 1   Pclass    889 non-null    int64
 2   Sex       889 non-null    object
 3   Age       889 non-null    float64
 4   SibSp     889 non-null    int64
 5   Parch     889 non-null    int64
 6   Fare      889 non-null    float64
 7   Embarked  889 non-null    object
dtypes: float64(2), int64(4), object(2)
memory usage: 62.5+ KB

In [18]:
df.head(1)

   Survived  Pclass   Sex   Age  SibSp  Parch  Fare Embarked
0         0       3  male  22.0      1      0  7.25        S

In [19]:
x=df.drop(columns=["Survived"])
y=df["Survived"]

In [20]:
x.head()

   Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0       3    male  22.0      1      0   7.2500        S
1       1  female  38.0      1      0  71.2833        C
2       3  female  26.0      0      0   7.9250        S
3       1  female  35.0      1      0  53.1000        S
4       3    male  35.0      0      0   8.0500        S

In [21]:
y.head()

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

In [22]:
from sklearn.model_selection import train_test_split

In [23]:
x_train, x_test, y_train, y_test = train_test_split( x, y, test_size=0.2)

In [24]:
x_train, x_test, y_train, y_test = train_test_split( x, y, test_size=0.2,random_state=42)

In [25]:
x_train, x_test, y_train, y_test = train_test_split( x, y, test_size=0.2,random_state=42,stratify=y)

In [26]:
print(x_test.shape)
print(x_train.shape)

(178, 7)
(711, 7)

In [27]:
from sklearn.neighbors import KNeighborsClassifier

model = KNeighborsClassifier()

model.fit(x_train, y_train)

ValueError: could not convert string to float: 'male'

In [28]:
x_train.head(1)

     Pclass   Sex   Age  SibSp  Parch     Fare Embarked
621       1  male  42.0      1      0  52.5542        S

In [29]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

In [30]:
cat_cols=["Sex","Embarked"]

In [31]:
# ct= ColumnTransformer([('cat',OneHotEncoder(sparse_output=False),cat_cols)
#            remainder='passthrough'])
# x_train_final=ct.fit_transform(x_train)
# x_test_final=ct.transform(x_test)

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

cat_cols = ['Sex', 'Embarked']

ct = ColumnTransformer([
    ('cat', OneHotEncoder(sparse_output=False), cat_cols)
], remainder='passthrough')

x_train_final = ct.fit_transform(x_train)
x_test_final = ct.transform(x_test)

In [32]:
x_train.shape
x_train_final.shape

(711, 10)

In [33]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

In [34]:
model=KNeighborsClassifier()
model.fit(x_train_final,y_train)

KNeighborsClassifier()

In [55]:
model = KNeighborsClassifier()
model.fit(x_train_final, y_train)
y_pre = model.predict(x_test_final)
print(accuracy_score(y_test, y_pre))

0.6741573033707865